name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Ruby (for CocoaPods if needed)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Install CocoaPods Dependencies
      run: |
        if [ -f "Podfile" ]; then
          pod install
        fi

    - name: Build and Test
      run: |
        if [ -f "Cyber-Sudoku---iOS.xcworkspace" ]; then
          xcodebuild -workspace Cyber-Sudoku---iOS.xcworkspace \
                     -scheme Cyber-Sudoku---iOS \
                     -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
                     clean test | xcpretty
        else
          xcodebuild -project Cyber-Sudoku---iOS.xcodeproj \
                     -scheme Cyber-Sudoku---iOS \
                     -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
                     clean test | xcpretty
        fi
      env:
        LANG: en_US.UTF-8
